Continue working on adjusting circle CI config (#163)
Pull the long multi-line commands into their own files for simpler yaml code. Pull each step into a command (or put commands together) so that we don't need to repeat any code.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,18 +3,12 @@ orbs:
   ruby: circleci/ruby@0.1.2
   slack: circleci/slack@3.4.2
 
-jobs:
-  build_and_test:
-    working_directory: ~/emma-sax4.github.io
-    docker:
-      - image: circleci/ruby:2.6-node
+commands:
+  configure_bundler:
     steps:
-      - checkout
       - run:
           name: Configure Bundler
-          command: |
-            echo "export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d ' ')" >> $BASH_ENV; source $BASH_ENV
-            gem install bundler
+          command: bash .circleci/configure-bundler.sh
       - restore_cache:
           key: bundler-cache-{{ checksum "Gemfile.lock" }}
       - run:
@@ -22,119 +16,89 @@ jobs:
           command: bundle install --path vendor/bundle
       - save_cache:
           key: bundler-cache-{{ checksum "Gemfile.lock" }}
-          paths:
-            - vendor/bundle
+          paths: [ vendor/bundle ]
+  jekyll_build:
+    steps:
       - run:
           name: Jekyll Build
           command: JEKYLL_ENV=production bundle exec jekyll build --destination ./site
+  html_proofer:
+    steps:
       - run:
           name: HTML Proofer
-          command: |
-            bundle exec htmlproofer \
-            --assume-extension \
-            --allow-hash-href \
-            --internal-domains /emmasax4.info/ \
-            --url-ignore /linkedin/,/digikey/ \
-            ./site \
-            || echo "HTML Proofer failed. Please investigate the failures."
+          command: bash .circleci/html-proofer.sh || echo "HTML Proofer failed. Please investigate the failures."
+  github_pages_deploy:
+    steps:
+      - deploy:
+          name: Deploy to GitHub Pages
+          command: bash .circleci/github-pages-deploy.sh
+  slack_build_notification:
+    steps:
       - run:
-          name: Slack - Creating Custom Message
-          command: |
-            if [ -z $CIRCLE_PULL_REQUESTS ]; then
-              m="Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME@$CIRCLE_BRANCH by $CIRCLE_USERNAME"
-            else
-              m="Build #$CIRCLE_BUILD_NUM of $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME@$CIRCLE_BRANCH in PR $CIRCLE_PULL_REQUESTS by $CIRCLE_USERNAME"
-            fi
-            echo "export SLACK_MESSAGE='$m'" >> $BASH_ENV; source $BASH_ENV
+          name: Slack - Generating Custom Message
+          command: bash .circleci/generate-slack-message.sh
       - slack/status:
           success_message: $SLACK_MESSAGE passed.
           failure_message: $SLACK_MESSAGE failed.
           include_job_number_field: false
           include_project_field: false
-
-  deploy:
-    working_directory: ~/emma-sax4.github.io
-    docker:
-      - image: circleci/ruby:2.6-node
+  slack_deploy_notification:
     steps:
-      - checkout
-      - run:
-          name: Configure Bundler
-          command: |
-            echo "export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d ' ')" >> $BASH_ENV; source $BASH_ENV
-            gem install bundler
-      - restore_cache:
-          key: bundler-cache-{{ checksum "Gemfile.lock" }}
-      - run:
-          name: Bundle Install
-          command: bundle install --path vendor/bundle
-      - save_cache:
-          key: bundler-cache-{{ checksum "Gemfile.lock" }}
-          paths:
-            - vendor/bundle
-      - run:
-          name: Jekyll Build
-          command: JEKYLL_ENV=production bundle exec jekyll build --destination ./
-      - deploy:
-          name: Deploy to GitHub Pages
-          command: |
-            git config user.name "$USER_NAME"
-            git config user.email "$USER_EMAIL"
-
-            git checkout master
-            git pull origin master
-
-            find . -maxdepth 1 ! -name "site" ! -name ".git" -exec rm -rf {} \;
-            mv ./site/* .
-            rm -R ./site/
-
-            git add -fA
-            git commit -m "Deploy to emma-sax4/emma-sax4.github.io.git:master via CircleCI"
-            git push origin master
       - slack/status:
           success_message: Successfully deployed to GitHub Pages.
           failure_message: Error deploying to GitHub Pages.
           include_job_number_field: false
           include_project_field: false
 
+jobs:
+  test:
+    working_directory: ~/emma-sax4.github.io
+    docker:
+      - image: circleci/ruby:2.6.5
+    steps:
+      - checkout
+      - configure_bundler
+      - jekyll_build
+      - html_proofer
+      - slack_build_notification
+  deploy:
+    working_directory: ~/emma-sax4.github.io
+    docker:
+      - image: circleci/ruby:2.6.5
+    steps:
+      - checkout
+      - configure_bundler
+      - jekyll_build
+      - github_pages_deploy
+      - slack_deploy_notification
+
 workflows:
   version: 2
   develop:
     jobs:
-      - build_and_test:
+      - test:
           filters:
             branches:
               ignore: [ release, master ]
   release:
     jobs:
-      - build_and_test:
+      - test:
           filters:
             branches:
               only: [ release ]
       - deploy:
-          requires: [ build_and_test ]
+          requires: [ test ]
           filters:
             branches:
               only: [ release ]
   nightly_cron:
     jobs:
-      - build_and_test
+      - test
       - deploy:
-          requires: [ build_and_test ]
+          requires: [ test ]
     triggers:
       - schedule:
           cron: "0 6 * * *" # 06:00 UTC => 00:00 CST
-          filters:
-            branches:
-              only: [ release ]
-  evening_cron:
-    jobs:
-      - build_and_test
-      - deploy:
-          requires: [ build_and_test ]
-    triggers:
-      - schedule:
-          cron: "0 1 * * *" # 01:00 UTC => 19:00 CST
           filters:
             branches:
               only: [ release ]
