Try this

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -13,16 +13,16 @@ jobs:
       - run:
           name: Configure Bundler
           command: |
-            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
+            echo "export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d ' ')" >> $BASH_ENV
             source $BASH_ENV
             gem install bundler
       - restore_cache:
-          key: bundle-cache-{{ checksum Gemfile.lock }}
+          key: bundle-cache-{{ checksum "Gemfile.lock" }}
       - run:
           name: Bundle Install
           command: bundle install --path vendor/bundle
       - save_cache:
-          key: bundle-cache-{{ checksum Gemfile.lock }}
+          key: bundle-cache-{{ checksum "Gemfile.lock" }}
           paths:
             - vendor/bundle
       - run:
@@ -37,9 +37,9 @@ jobs:
             --internal-domains /emmasax4.info/ \
             --url-ignore /linkedin/,/digikey/ \
             ./site \
-            || echo 'HTML Proofer failed. Please investigate the failures.'
+            || echo "HTML Proofer failed. Please investigate the failures."
       - slack/status:
-          success_message: 'Build #${CIRCLE_BUILD_NUM} of branch `${CIRCLE_BRANCH}` succeeded.'
-          failure_message: 'Build #${CIRCLE_BUILD_NUM} of branch `${CIRCLE_BRANCH}` failed.'
+          success_message: "Build #${CIRCLE_BUILD_NUM} of branch `${CIRCLE_BRANCH}` succeeded."
+          failure_message: "Build #${CIRCLE_BUILD_NUM} of branch `${CIRCLE_BRANCH}` failed."
           include_job_number_field: false
           include_project_field: false
